- package.json
see https://github.com/sindresorhus/escape-goat
> add escape-goat

- package.json
error info: 
```
Compress error
{ SyntaxError: Unexpected token: name (context)
}
ERROR  Failed to compile with 1 errors                                                                                                                                                         10:20:31
error
Unexpected token: name (context)
```
> add: striptags

- package.json
query-string depend on. https://github.com/sindresorhus/query-string/blob/master/package.json#L38
> split-on-first arrow function

- package.json
> add: array-move

- package.json
> add dot-prop

- package.json
- ky@0.5.2
- seinjs@1.1.14
> seinjs@1.1.14 暂未公开源码
> feat: add seinjs and ky

- package.json
> Add antd-table-infinity

- package.json
> add ansi-colors@^3.2.4

- package.json
> fix: all versions of react-dnd and dependencies should be configured

- package.json
https://github.com/d3/d3-array/blob/master/src/count.js#L2
> feat:add d3-array

- package.json
> fix: issue for https://github.com/umijs/umi/issues/3409

- package.json
打包后，getCurrentSourceNodeOptions中出现扩展运算符...
> react-dnd-html5-backend@8.0.3

- package.json
一个深度神经网络识别库，可以用于浏览器和Node环境，支持CPU/GPU
> 新增Brain.js

- package.json
> add webtorrent and add flv.js

- package.json
Reverts umijs/es5-imcompatible-versions#73
> Revert "add webtorrent and add flv.js"

- package.json
> add pearplayer

- package.json
already had config: query-string 6.0.0, now add 7.0.0 config
> feat: fix query-string 7.0.0 +

- package.json
add react-spring/rafz、react-spring/shared
> add react-spring/rafz、react-spring/shared

- package.json
Reverts umijs/es5-imcompatible-versions#112
> Revert "feat: add ip-bigint"

- package.json
添加 gpt-tokenizer，它的产物从一开始就是 es2022 的
> feat: add gpt-tokenizer

- package.json
readable-stream 产物里有 async generator
> feat: add readable-stream
